const mediumQuestions = [
  {
    text: "Solve for x: 3x - 5 = 16",
    options: ["x = 7", "x = 6", "x = 5", "x = 4"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["algebra", "linear equations"],
  },
  {
    text: "What is the circumference of a circle with a diameter of 14 cm? (Use π = 3.14)",
    options: ["43.96 cm", "44 cm", "42 cm", "45 cm"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["geometry", "circles"],
  },
  {
    text: "Simplify: 2(x + 3) + 4(x - 1)",
    options: ["6x + 1", "6x + 5", "6x + 2", "6x + 3"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["algebra", "simplification"],
  },
  {
    text: "What is the perimeter of a triangle with sides 5 cm, 12 cm, and 13 cm?",
    options: ["30 cm", "25 cm", "28 cm", "32 cm"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["geometry", "triangles"],
  },
  {
    text: "Factorize: x² + 5x + 6",
    options: [
      "(x + 2)(x + 3)",
      "(x + 1)(x + 6)",
      "(x - 2)(x + 3)",
      "(x + 2)(x - 3)",
    ],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["algebra", "factorization"],
  },
  {
    text: "Solve for y: 3y + 4 = 19",
    options: ["y = 5", "y = 6", "y = 4", "y = 7"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["algebra", "linear equations"],
  },
  {
    text: "What is the volume of a cube with a side length of 4 cm?",
    options: ["64 cm³", "16 cm³", "32 cm³", "48 cm³"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["geometry", "cubes"],
  },
  {
    text: "What is the mean of the following set of numbers: 5, 10, 15, 20, 25?",
    options: ["15", "20", "25", "30"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["statistics", "mean"],
  },
  {
    text: "If a = 9 and b = 12, what is the value of a + b?",
    options: ["21", "22", "20", "23"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["arithmetic", "addition"],
  },
  {
    text: "What is the next number in the sequence: 3, 6, 12, 24, ...?",
    options: ["30", "36", "48", "42"],
    correctOptionIndex: 2,
    difficulty: 2,
    tags: ["algebra", "sequences"],
  },
  {
    text: "What is the surface area of a cube with a side length of 5 cm?",
    options: ["150 cm²", "125 cm²", "100 cm²", "200 cm²"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["geometry", "cubes"],
  },
  {
    text: "What is the value of 3³?",
    options: ["9", "27", "18", "36"],
    correctOptionIndex: 1,
    difficulty: 2,
    tags: ["exponents", "arithmetic"],
  },
  {
    text: "Simplify: 4(x + 2) - 3(x - 1)",
    options: ["x + 11", "x + 9", "x + 7", "x + 5"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["algebra", "simplification"],
  },
  {
    text: "In the equation y = 2x + 5, what is the slope?",
    options: ["2", "5", "1", "0"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["algebra", "linear equations"],
  },
  {
    text: "What is the value of x if x² - 9 = 0?",
    options: ["x = ±3", "x = ±4", "x = ±2", "x = ±5"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["algebra", "quadratic equations"],
  },
  {
    text: "How many degrees are in the sum of the interior angles of a hexagon?",
    options: ["720°", "540°", "360°", "480°"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["geometry", "polygons"],
  },
  {
    text: "What is the value of √64?",
    options: ["8", "6", "7", "9"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["square roots", "arithmetic"],
  },
  {
    text: "What is 15% of 200?",
    options: ["30", "25", "20", "35"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["percentages", "arithmetic"],
  },
  {
    text: "If the side length of a square is tripled, by what factor does the area increase?",
    options: ["3", "6", "9", "12"],
    correctOptionIndex: 2,
    difficulty: 2,
    tags: ["geometry", "squares"],
  },
  {
    text: "What is the probability of rolling a 4 on a standard six-sided die?",
    options: ["1/6", "1/3", "1/4", "1/2"],
    correctOptionIndex: 0,
    difficulty: 2,
    tags: ["probability", "statistics"],
  },
];

const hardQuestions = [
  {
    text: "Solve for x: 5x/2 - 3 = 7",
    options: ["x = 4", "x = 2", "x = 5", "x = 8"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["algebra", "linear equations"],
  },
  {
    text: "What is the area of a circle with a radius of 10 cm? (Use π = 3.14)",
    options: ["314 cm²", "157 cm²", "31.4 cm²", "100 cm²"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["geometry", "circles"],
  },
  {
    text: "Simplify: 3x² - 2x + 4 - (x² - 2x + 5)",
    options: ["2x² - 1", "4x² + 1", "2x² + 9", "4x² - 1"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["algebra", "simplification"],
  },
  {
    text: "What is the length of the diagonal of a rectangle with length 6 cm and width 8 cm?",
    options: ["10 cm", "14 cm", "12 cm", "11 cm"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["geometry", "rectangles"],
  },
  {
    text: "Factorize: 4x² - 25",
    options: [
      "(2x + 5)(2x - 5)",
      "(4x + 5)(x - 5)",
      "(2x - 5)²",
      "(2x + 5)(4x - 5)",
    ],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["algebra", "factorization"],
  },
  {
    text: "Solve for y: 4y/5 + 2 = 6",
    options: ["y = 5", "y = 6", "y = 12", "y = 18"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["algebra", "linear equations"],
  },
  {
    text: "What is the volume of a cylinder with a radius of 3 cm and a height of 5 cm? (Use π = 3.14)",
    options: ["45 cm³", "141.3 cm³", "282.6 cm³", "226.2 cm³"],
    correctOptionIndex: 1,
    difficulty: 3,
    tags: ["geometry", "cylinders"],
  },
  {
    text: "What is the median of the following set of numbers: 3, 8, 1, 4, 6, 9, 10?",
    options: ["6", "4", "5", "8"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["statistics", "median"],
  },
  {
    text: "If a = 7 and b = 24, what is the value of √(a² + b²)?",
    options: ["25", "31", "17", "23"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["geometry", "Pythagorean theorem"],
  },
  {
    text: "What is the next number in the sequence: 7, 14, 28, 56, ...?",
    options: ["70", "112", "84", "128"],
    correctOptionIndex: 1,
    difficulty: 3,
    tags: ["algebra", "sequences"],
  },
  {
    text: "What is the surface area of a sphere with a radius of 5 cm? (Use π = 3.14)",
    options: ["314 cm²", "157 cm²", "3140 cm²", "785 cm²"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["geometry", "spheres"],
  },
  {
    text: "What is the value of 2⁷?",
    options: ["49", "128", "64", "256"],
    correctOptionIndex: 1,
    difficulty: 3,
    tags: ["exponents", "algebra"],
  },
  {
    text: "Simplify: 7(x - 2) - 3(2x + 1)",
    options: ["x - 17", "x - 13", "x + 17", "x + 13"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["algebra", "simplification"],
  },
  {
    text: "In the equation y = 3x² - 4x + 7, what type of function is this?",
    options: ["Linear", "Quadratic", "Cubic", "Exponential"],
    correctOptionIndex: 1,
    difficulty: 3,
    tags: ["algebra", "functions"],
  },
  {
    text: "What is the value of x if 2x² - 8x + 6 = 0?",
    options: ["x = 2 ± √2", "x = 3 ± √1", "x = 1 ± √3", "x = 4 ± √2"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["algebra", "quadratic equations"],
  },
  {
    text: "How many degrees are in the sum of the interior angles of a pentagon?",
    options: ["360°", "540°", "720°", "900°"],
    correctOptionIndex: 1,
    difficulty: 3,
    tags: ["geometry", "polygons"],
  },
  {
    text: "What is the value of √225?",
    options: ["15", "25", "12", "18"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["square roots", "algebra"],
  },
  {
    text: "What is 20% of 360?",
    options: ["72", "60", "80", "90"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["percentages", "arithmetic"],
  },
  {
    text: "If the side length of a cube is doubled, by what factor does the volume increase?",
    options: ["2", "4", "8", "16"],
    correctOptionIndex: 2,
    difficulty: 3,
    tags: ["geometry", "cubes"],
  },
  {
    text: "What is the probability of drawing an ace from a standard deck of 52 cards?",
    options: ["1/13", "1/26", "1/52", "1/4"],
    correctOptionIndex: 0,
    difficulty: 3,
    tags: ["probability", "statistics"],
  },
];
